### PR TITLE
Better Wording

### PR DESCRIPTION
**Pull request by RyanZim**
Let's be dignified.

### CODE REVIEW

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by RyanZim** [comment]
@mde ping?

**Comment by mde** [comment]
I am actually a very big fan of judicious use of profanity. However, if you feel strongly this is a good change, we can go ahead and merge it.

**Pull request merged**
