### PR TITLE
Use npm for "Get It" link

### PR DESCRIPTION
**Pull request by TimothyGu**

### CODE REVIEW

**Comment by TimothyGu** [comment]
Also we should consider moving EJS stuff into a separate repo, so that contributors don't need to look for a separate repo for the website. This also makes permission management easier.

**Comment by mde** [comment]
I thought about using the NPM page for this, but there's nothing actionable on that page. If you want to install via NPM, you just do it via the command line. At least with the release page, people who want to download it for the browser can do that.

I'm not opposed to multiple buttons, but the NPM page isn't really useful for anything other than letting people know what the package name is, and for stats. We already have `npm install ejs` prominently under Getting Started, and I'm not sure what else we could do there.

Maybe three buttons: Latest Release, GitHub, and NPM? Seems kinda busy.

Also I sent a message out to the 'ejs' user on GH last week because the account is mostly dormant, but I've gotten no response yet. GH has a flat namespace where both users and orgs are shared, so if we want that ideal org name, we'll either have to get that user's acquiescence, or get GH to evict them. I'm open to other org names, but I'd like to try for the ideal one first.

**Comment by TimothyGu** [comment]
I really don't like GitHub release as there is literally 0 people who would download the release tarball, and not many people who would download the browserified files without first reading how to use them.

How about linking it to "Getting Started" page?

Yeah for the organization stuff there doesn't seem to be a better thing to do than this, though I'm not sure if GH would evict the user as it's kind of impolite.

**Comment by mde** [comment]
Linking to "Getting Started" sounds better -- although I think we need a more obvious way than a subtle link in the explanation text for people to go download the browser files.

GH definitely evicts users who are just squatting on their permalink without doing anything with it. That's how we got Geddy into the "geddy" org. The issue here is that the user isn't 100% inactive -- just 99%. :)

**Comment by mde** [comment]
Okay, I've made this change in 2cbb65b2cd5c5b5899f4450547b7c52213a603a5 and pushed it up to the site.

**Pull request closed without merging**
